### ISSUE TITLE
Got exceptions Java.Lang.RuntimeException: An error occurred while executing doInBackground()

### ISSUE THREAD

**Issue by crystallove** [matheusneder/Xamarin.Forms.ImagePicker#9]
Hi guys,

This seem to work but ..I got exception after pick image from source or take a picture via camera. When I tried to debug, It came to 'Crop ' screen after throw the exception. Attachment is more details.
![img_20190121_155931](https://user-images.githubusercontent.com/6846206/51463682-6945e900-1d96-11e9-8e45-0e02f6501bde.jpg)
![img_20190121_155944](https://user-images.githubusercontent.com/6846206/51463683-69de7f80-1d96-11e9-89ed-f0896934a937.jpg)

Hope It'll work at next release :)

**Comment by dai15002** [comment]
I am having the same problem. No fix yet, so this library is useless.
